export const SHOW_ERROR = 'SHOW_ERROR';
export const STOP_FETCHING = 'STOP_FETCHING';
export const START_FETCHING = 'START_FETCHING';
export const CONNECTION_FAILED = 'CONNECTION_FAILED';
export const CONNECTION_SUCCEEDED = 'CONNECTION_SUCCEEDED';
export const COULD_ACCESS_ACCOUNT = 'COULD_ACCESS_ACCOUNT';
export const COULD_NOT_ACCESS_ACCOUNT = 'COULD_NOT_ACCESS_ACCOUNT';

export const RECEIVE_ACCOUNT = 'RECEIVE_ACCOUNT';
export const RECEIVE_ETHER_BALANCE = 'RECEIVE_ETHER_BALANCE';
export const CREATE_NEW_RAFFLE = 'CREATE_NEW_RAFFLE';
export const CREATE_NEW_RAFFLE_RESET = 'CREATE_NEW_RAFFLE_RESET';

export const ADD_RAFFLE = 'ADD_RAFFLE';
export const RECEIVE_RAFFLE = 'RECEIVE_RAFFLE';
